# Generated by Django 3.0.7 on 2020-07-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200716_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='webaddress',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion Web'),
        ),
    ]
