# Generated by Django 3.0.7 on 2020-07-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200717_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='webaddress',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección Web'),
        ),
    ]
